artifact_uri: file:d:/For_Job/floorplan-ai-analyzer/runs/mlflow/214803993010467134/04ba29c50bc64c9c8d8be94c67bf481c/artifacts
end_time: 1773301992393
entry_point_name: ''
experiment_id: '214803993010467134'
lifecycle_stage: active
run_id: 04ba29c50bc64c9c8d8be94c67bf481c
run_name: floorplan_yolo
source_name: ''
source_type: 4
source_version: ''
start_time: 1773301933835
status: 3
tags: []
user_id: tharu
