artifact_location: file:d:/For_Job/floorplan-ai-analyzer/runs/mlflow/0
creation_time: 1773301930711
experiment_id: '0'
last_update_time: 1773301930711
lifecycle_stage: active
name: Default
workspace: default
